---
############
# Env Vars #
############
env:
  commonjs: true
  node: true
  es6: false

###############
# Global Vars #
###############
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly

###############
# Parser vars #
###############
parserOptions:
  ecmaVersion: 2018

#########
# Rules #
#########
rules:
  semi:
    - 2
    - never
  func-names: 0
  no-param-reassign: 0
  no-multi-str: 0
  no-unused-vars:
    - 2
    - vars: all
      args: after-used
  no-console: 2
  consistent-return: 0
