---
############
# Env Vars #
############
env:
  commonjs: true
  node: true

###############
# Global Vars #
###############
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly

###############
# Parser vars #
###############
parserOptions:
  ecmaVersion: 2018

###########
# Plugins #
###########
plugins:
  - 'prettier'

#########
# Rules #
#########
rules: {
  "semi": ["error", "never"],
  "func-names": 0,
  "no-param-reassign": 0,
  "no-multi-str": 0,
  "no-unused-vars": ["error", { "argsIgnorePattern": "^_" }],
  "no-console": ["error", { "allow": ["tron"] }],
  "consistent-return": 0
}
